const CASUAL_PAGES = [
    "France",
    "Paris",
    "Europe",
    "États-Unis",
    "Japon",
    "Chine",
    "Italie",
    "Espagne",
    "Allemagne",
    "Canada",
    "Brésil",
    "Afrique",
    "Océan",
    "Mer",
    "Montagne",
    "Forêt",
    "Désert",
    "Plage",
    "Île",
    "Ville",
    "Village",
    "Maison",
    "École",
    "Université",
    "Hôpital",
    "Restaurant",
    "Cinéma",
    "Musée",
    "Bibliothèque",
    "Supermarché",
    "Aéroport",
    "Gare",

    "Chat",
    "Chien",
    "Cheval",
    "Vache",
    "Cochon",
    "Mouton",
    "Poule",
    "Canard",
    "Lapin",
    "Souris",
    "Lion",
    "Tigre",
    "Éléphant",
    "Girafe",
    "Zèbre",
    "Singe",
    "Ours",
    "Loup",
    "Renard",
    "Dauphin",
    "Baleine",
    "Requin",
    "Poisson",
    "Aigle",
    "Hibou",
    "Serpent",
    "Tortue",
    "Grenouille",
    "Papillon",
    "Abeille",

    "Pomme",
    "Banane",
    "Orange",
    "Fraise",
    "Raisin",
    "Citron",
    "Tomate",
    "Carotte",
    "Pomme de terre",
    "Oignon",
    "Salade",
    "Pain",
    "Fromage",
    "Lait",
    "Œuf",
    "Riz",
    "Pâtes",
    "Pizza",
    "Hamburger",
    "Sandwich",
    "Chocolat",
    "Glace",
    "Gâteau",
    "Café",
    "Thé",
    "Eau",
    "Jus de fruits",

    "Voiture",
    "Vélo",
    "Moto",
    "Bus",
    "Train",
    "Avion",
    "Bateau",
    "Métro",
    "Tramway",
    "Camion",
    "Route",
    "Pont",
    "Tunnel",

    "Téléphone",
    "Smartphone",
    "Ordinateur",
    "Internet",
    "Télévision",
    "Radio",
    "Appareil photo",
    "Jeu vidéo",
    "Console de jeux vidéo",
    "Robot",
    "Intelligence artificielle",
    "Application mobile",
    "Réseau social",
    "YouTube",
    "Google",
    "Netflix",

    "Football",
    "Basket-ball",
    "Tennis",
    "Rugby",
    "Natation",
    "Cyclisme",
    "Boxe",
    "Ski",
    "Surf",
    "Course à pied",
    "Jeux olympiques",
    "Stade",
    "Ballon",

    "Musique",
    "Chanson",
    "Guitare",
    "Piano",
    "Batterie",
    "Violon",
    "Concert",
    "Danse",
    "Film",
    "Dessin animé",
    "Bande dessinée",
    "Livre",
    "Roman",
    "Poésie",
    "Peinture",
    "Photographie",

    "Soleil",
    "Lune",
    "Terre",
    "Mars",
    "Jupiter",
    "Étoile",
    "Planète",
    "Univers",
    "Galaxie",
    "Fusée",
    "Astronaute",

    "Histoire",
    "Géographie",
    "Mathématiques",
    "Physique",
    "Chimie",
    "Biologie",
    "Philosophie",
    "Art",
    "Science",
    "Médecine",
    "Cuisine",
    "Sport",
    "Religion",
    "Politique",
    "Économie",

    "Tour Eiffel",
    "Statue de la Liberté",
    "Grande Muraille",
    "Pyramide de Khéops",
    "Colisée",
    "Mont Everest",
    "Sahara",
    "Amazonie",
    "Nil",
    "Océan Pacifique",

    "Noël",
    "Halloween",
    "Anniversaire",
    "Mariage",
    "Vacances",
    "Week-end",
    "Famille",
    "Amitié",
    "Amour",
    "Travail",
    "Argent",
    "Temps",
    "Sommeil",
    "Rêve",
    "Météo",
    "Pluie",
    "Neige",
    "Vent",
    "Feu",
    "Air",
"Rouge",
"Bleu",
"Vert",
"Jaune",
"Noir",
"Blanc",
"Rose",
"Violet",
"Orange",
"Gris",
"Marron",
    "Minecraft",
    "Pokémon",
    "Super Mario",
    "Harry Potter",
    "Star Wars",
    "Disney",
    "Marvel Comics",
    "Le Seigneur des anneaux",
    "Dragon Ball",
    "One Piece",
"T-shirt",
"Pantalon",
"Jean",
"Chaussure",
"Botte",
"Veste",
"Manteau",
"Pull",
"Casquette",
"Chapeau",
"Robe",
"Jupe",
"Cravate",
"Cuisine",
"Salon",
"Chambre",
"Salle de bains",
"Garage",
"Jardin",
"Balcon",
"Toit",
"Porte",
"Fenêtre",
"Escalier",
"Table",
"Chaise",
"Canapé",
"Lit",
"Lampe",
"Horloge",
"Télécommande",
"Clavier",
"Souris",
"Écran",
"Sac à dos",
"Valise",
"Bouteille",
"Verre",
"Assiette",
"Fourchette",
"Couteau",
"Cuillère",
"Arbre",
"Fleur",
"Rose",
"Tulipe",
"Herbe",
"Champignon",
"Volcan",
"Cascade",
"Rivière",
"Lac",
"Grotte",
"Nuage",
"Arc-en-ciel",
"Tempête",
"Orage",
"Médecin",
"Infirmier",
"Professeur",
"Policier",
"Pompier",
"Cuisinier",
"Boulanger",
"Agriculteur",
"Ingénieur",
"Programmeur",
"Journaliste",
"Pilote",
"Architecte",
"Vétérinaire",
"Fortnite",
"Roblox",
"Tetris",
"Pac-Man",
"Sonic",
"Crash Bandicoot",
"The Legend of Zelda",
"Animal Crossing",
"League of Legends",
"Rocket League",
"Titanic",
"Avatar",
"Jurassic Park",
"Le Roi lion",
"Toy Story",
"Shrek",
"La Reine des neiges",
"Spider-Man",
"Batman",
"Iron Man",
"Apple",
"Samsung",
"Nike",
"Adidas",
"Coca-Cola",
"Pepsi",
"McDonald's",
"Burger King",
"Amazon",
"Microsoft",
"Main",
"Bras",
"Jambe",
"Pied",
"Œil",
"Oreille",
"Nez",
"Bouche",
"Dent",
"Cerveau",
"Cœur",
"Poumon",
"Estomac",
"Joie",
"Tristesse",
"Colère",
"Peur",
"Surprise",
"Stress",
"Bonheur",
"Confiance",
"Courage",
"Curiosité",
"Koala",
"Kangourou",
"Panda",
"Pingouin",
"Phoque",
"Chameau",
"Lama",
"Paresseux",
"Autruche",
"Paon",
"Crocodile",
"Hippopotame",
"Rhinocéros",
"Guépard"

];